# Site settings
title: "BlueCloud's Lab"
description: "A Jekyll Theme designed for Podcasters"
podcast-description: "A Jekyll Theme designed for Podcasters. This is your podcast's summary."
url:  "https://b1uec1oud.github.io//" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Taehoon Kimmily"
  email: "th951113@gmail.com"
  url: "https://b1uec1oud.github.io/"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username:
  card: 
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover_Small.png
social:
  name: Taehoon Kim
  links:
    - https://github.com/B1ueC1oud
    - https://sites.google.com/ajou.ac.kr/bluecloud/%ED%99%88?pli=1&authuser=1
    - https://www.linkedin.com/in/TaehoonKimmily
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: BlueCloud's Lab
podcast_author: Taehoon Kimmily
podcast_email: th951113@gmail.com
podcast_subtitle: "A Jekyll Theme designed for Podcasters"
podcast_summary: "A Jekyll Theme designed for Podcasters. This is your podcast's summary."
podcast_description: "A Jekyll Theme designed for Podcasters. This is your podcast's description."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2022-05-09" #Launch date of your podcast
podcast_copyright: "&#xA9;Alessio Franceschi"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover_Small.png"
